name: linwood
grade: stable
version: '1.6.1'
adopt-info: linwood
base: core22
confinement: strict
compression: lzo
architectures:
  - build-on: [amd64]
    build-for: [amd64]

slots:
  linwood:
    interface: dbus
    bus: session
    name: dev.linwood.butterfly

apps:
  linwood:
    command: butterfly
    extensions: [gnome]
    plugs:
      - home
      - optical-drive
      - removable-media
    common-id: dev.linwood.butterfly
    desktop: usr/share/applications/dev.linwood.butterfly.desktop

parts:
  linwood:
    plugin: flutter
    source: https://github.com/LinwoodDev/Butterfly.git
    source-tag: v$SNAPCRAFT_PROJECT_VERSION
    parse-info: [usr/share/metainfo/dev.linwood.butterfly.appdata.xml]
    build-packages:
      - curl
    
      
  
      



