name: linwood
grade: stable
version: '1.6.1'
summary: Powerful, minimalistic, cross-platform, opensource note-taking app.
description: |
  Butterfly is a note app where your ideas come first. You can paint, add texts and export them easily on every device.
base: core22
confinement: strict
compression: lzo
architectures:
  - build-on: amd64
  - build-on: armhf
  - build-on: arm64

apps:
  linwood:
    command: butterfly
    extensions: [gnome]
    plugs:
      - home
      - network
      - optical-drive
      - removable-media
    common-id: dev.linwood.butterfly
    desktop: usr/share/applications/dev.linwood.butterfly.desktop

parts:
  linwood:
    plugin: flutter
    source: https://github.com/LinwoodDev/Butterfly.git
    build-packages:
      - build-essential
      - curl
    stage-packages:
      - libjsoncpp25
    parse-info: [usr/share/metainfo/dev.linwood.butterfly.appdata.xml]
    
      
#override-build: |
  #craftctl default
  #chmod a+x ./butterfly
  
#slots:
  #linwood:
    #interface: dbus
    #bus: session
    #name: dev.linwood.butterfly

